spring:
  application:
    name: WebAPI
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    url: jdbc:sqlite:SQLiteDataBase.db
  servlet:
    encoding:
      charset: UTF-8
      force: true

server:
  port: 36987

logging:
  pattern:
    level: "%5p %X{RequestID}"
    # https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.custom-log-configuration