spring:
  application:
    name: WebAPI
  threads:
    virtual:
      enabled: true
server:
  port: 36987
logging:
  pattern:
    level: "%5p %X{RequestID}"
    # https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.custom-log-configuration